// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tezwoygewdpwivrxusix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlendveWdld2Rwd2l2cnh1c2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDQ4MDYsImV4cCI6MjA3MjQ4MDgwNn0.PW7vCHs8IxLVM6kRB_DYIDTngBbZ1gZNI5xd-wa4xoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});